[tool.poetry]
name = "text-adventure"
version = "0.1.0"
description = "A text-based roguelike including dungeons, monsters and magic 🎉"
authors = ["AlexisMoins <moinsalexis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.0.1"
PyYAML = "^6.0"
jedi = "^0.18.1"
autopep8 = "^1.6.0"

[tool.poetry.dev-dependencies]

[tool.autopep8]
# max_line_length = 120
# ignore = "E501,W6"  # or ["E501", "W6"]
# in-place = true
# recursive = true
# aggressive = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
